// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DataSource struct {
	Filepath         string
	Type             string
	OriginalFilename string
	Size             int64
	CreatedAt        pgtype.Timestamptz
}

type Point struct {
	Geom               interface{}
	Visited            pgtype.Timestamptz
	DataSourceFilepath string
}
