// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DataSource struct {
	Filepath         string             `json:"filepath"`
	Type             string             `json:"type"`
	OriginalFilename string             `json:"originalFilename"`
	Size             int64              `json:"size"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
}

type Point struct {
	Geom               interface{}        `json:"geom"`
	Visited            pgtype.Timestamptz `json:"visited"`
	DataSourceFilepath string             `json:"dataSourceFilepath"`
}
